Cypress hw2
Ira8694733/QA_Cypress pull request #6
Opened 2024-04-18 17:21 UTC by Ira8694733

2024-04-19 11:23 UTC, AgamSss requested changes

2024-04-19 11:23 UTC, AgamSss commented on cypress/e2e/test_HW_2.cy.js
> +        cy.xpath("//a[@routerlink='garage']").click();
Треба прибрати у пейджу

2024-04-19 11:23 UTC, AgamSss commented on cypress/e2e/test_HW_2.cy.js
> +        cy.wait (2000);
Прибрати вейт й замінити на очікування елементу котрий має інувати

2024-04-19 11:23 UTC, AgamSss commented on cypress/e2e/test_HW_2.cy.js
> +        cy.xpath("//a[@routerlink='/panel/profile']").click();
Прибрати в пейджу

2024-04-19 11:23 UTC, AgamSss commented on cypress/e2e/test_HW_2.cy.js
> +        cy.xpath("//button[@id='userNavDropdown']").click();
Прибрати в пейджу

2024-04-19 11:23 UTC, AgamSss commented on cypress/e2e/test_HW2.cy.js
> +        cy.xpath("//a[@routerlink='garage']").click();
Прибрати в пейджу

2024-04-19 11:23 UTC, AgamSss commented on cypress/e2e/test_HW2.cy.js
> +        cy.xpath("//a[@routerlink='/panel/profile']").click();
Прибрати в пейджу

2024-04-19 11:23 UTC, AgamSss commented on cypress/e2e/test_HW2.cy.js
> +        cy.xpath("//button[@id='userNavDropdown']").click();
Прибрати в пейджу

2024-04-19 11:23 UTC, AgamSss commented on cypress/e2e/test_HW2.cy.js
> +        cy.wait (2000);
прибрати вейт, замінити на очікування

2024-04-19 11:23 UTC, AgamSss commented on cypress/e2e/test_HW2.cy.js
> +        garageProfile.addCarBrand().select("Audi");
Дані краще записувати у змінних, й передавати як змінну.

2024-04-20 19:46 UTC, Ira8694733 commented on cypress/e2e/test_HW2.cy.js
> +        garageProfile.addCarBrand().select("Audi");
Done

2024-04-20 19:46 UTC, Ira8694733 commented on cypress/e2e/test_HW2.cy.js
> +        cy.wait (2000);
Done

2024-04-20 19:46 UTC, Ira8694733 commented on cypress/e2e/test_HW2.cy.js
> +        cy.xpath("//button[@id='userNavDropdown']").click();
Done

2024-04-20 19:46 UTC, Ira8694733 commented on cypress/e2e/test_HW2.cy.js
> +        cy.xpath("//a[@routerlink='/panel/profile']").click();
Done

2024-04-20 19:46 UTC, Ira8694733 commented on cypress/e2e/test_HW2.cy.js
> +        cy.xpath("//a[@routerlink='garage']").click();
Done

2024-04-20 19:46 UTC, Ira8694733 commented on cypress/e2e/test_HW_2.cy.js
> +        cy.xpath("//button[@id='userNavDropdown']").click();
Done

2024-04-20 19:47 UTC, Ira8694733 commented on cypress/e2e/test_HW_2.cy.js
> +        cy.xpath("//button[@id='userNavDropdown']").click();
Done

2024-04-20 19:47 UTC, Ira8694733 commented on cypress/e2e/test_HW_2.cy.js
> +        cy.xpath("//a[@routerlink='/panel/profile']").click();
Done

2024-04-20 19:47 UTC, Ira8694733 commented on cypress/e2e/test_HW_2.cy.js
> +        cy.wait (2000);
Done

2024-04-20 19:47 UTC, Ira8694733 commented on cypress/e2e/test_HW_2.cy.js
> +        cy.xpath("//a[@routerlink='garage']").click();
Done

2024-04-21 20:02 UTC, AgamSss approved these changes

2024-04-22 22:20 UTC, merged