Cypress hw api
Ira8694733/QA_Cypress pull request #9
Opened 2024-04-28 19:50 UTC by Ira8694733

2024-04-28 19:50 UTC, Ira8694733 commented
HW

2024-04-28 19:50 UTC, Ira8694733 commented
HW

2024-04-28 19:50 UTC, Ira8694733 commented
HW

2024-04-28 19:51 UTC, Ira8694733 commented
HW

2024-04-28 19:51 UTC, Ira8694733 commented
HW

2024-04-28 19:53 UTC, Ira8694733 commented
HW

2024-04-28 20:01 UTC, Ira8694733 commented
HW

2024-04-29 17:49 UTC, Ira8694733 reviewed
Review

2024-04-29 17:56 UTC, Ira8694733 commented
.

2024-04-29 18:03 UTC, Ira8694733 commented
checked conflicted items

2024-04-30 14:04 UTC, AgamSss requested changes

2024-04-30 14:04 UTC, AgamSss commented on cypress/e2e/test_API.cy.js
> +        cy.request({
ось тут краще дані передавати як змінні, наприклад хедери та баді, ми можемо передавати як дві окремі змінні й це підвищить читабельність коду

2024-04-30 14:04 UTC, AgamSss commented on cypress/e2e/test_API.cy.js
> +            const createdCar = allCars.find(car => car.brand === 'Audi' && car.model === 'TT');
теж саме бренди ми можемо оформлювати як змінні

2024-05-01 12:34 UTC, Ira8694733 commented
PR witout changes

2024-05-03 16:47 UTC, Ira8694733 reviewed
review

2024-05-03 17:13 UTC, closed without merging